# We need to setup different context root for the auth server so that we can store separate
# cookies for both the API gateway as well as the OAuth2 authorization server.
server:
  port: 8899
  contextPath: /userauth

security:
  user:
    password: password

logging:
  level:
    org.springframework.security: DEBUG

# Datasource and JPA configuration to be used for storing the OAuth authorization details
# and token store
spring:
  datasource:
    url: jdbc:mysql://mysqldb:3306/auth
    username: root
    password: password
    driver-class: com.mysql.jdbc.Driver
sleuth:
  enabled: true
  sampler:
    percentage: 1
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaregistry:8761/eureka/
---

spring:
  profiles: docker
# Datasource and JPA configuration to be used for storing the OAuth authorization details
# and token store
  datasource:
    url: jdbc:mysql://mysqldb:3306/auth
    username: root
    password: password
    driver-class: com.mysql.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: false
    hibernate:
      ddl-auto: create

eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaregistry:8761/eureka/