# The portal is the root app since all the UI (at /** path) is maintained here; so we don't provide
# any context root for the UI application
server:
  port: 8090
spring:
sleuth:
  enabled: true
  sampler:
    percentage: 1
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411

logging:
  level:
    org.springframework.security: DEBUG
eureka:
  client:
    serviceUrl:
      defaultZone: http://eurekaregistry:8761/eureka/
turbine:
  appConfig: task-webservice
  clusterNameExpression: "'default'"