server:
  port: 8761
sleuth:
  enabled: true
  sampler:
    percentage: 1
  zipkin:
    enabled: true

---

spring:
  profiles: docker
sleuth:
  enabled: true
  sampler:
    percentage: 1
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
