server:
  port: 8761
spring:
sleuth:
  enabled: true
  sampler:
    percentage: 1
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
# Defines the Eureka server that is used by the Netflix OSS components to use as the registry
# for server discovery
eureka:
  instance:
    hostname: eurekaregistry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaregistry:8761

---

spring:
  profiles: docker
sleuth:
  enabled: true
  sampler:
    percentage: 1
  zipkin:
    enabled: true
    baseUrl: http://zipkin:9411
eureka:
  instance:
    hostname: eurekaregistry
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://eurekaregistry:8761
